### Numpy
#### (Numerical python)

* Used for working with arrays
* in python we have lists that serve the purpose of arrays but they are slow to process
* numpy is incredible library to perfom mathematical and statistical operations due to its fast and memory efficient as it is optimized to work with latest cpu architectures
* numby eims to provide an array object that is upto 50x faster than traditional python lists.so processes can access and manupulate them very efficiently  

In [1]:
import numpy as np

#### Numpy Arrays

##### 0-D

In [2]:
a = 45
print(a)
print(type(a))

45
<class 'int'>


In [3]:
a=45
arr_0 = np.array(a)         #ndarray - n dimensional array 
print(arr_0)
print(type(arr_0))

45
<class 'numpy.ndarray'>


In [4]:
arr_0.ndim

0

In [5]:
arr_0.shape

()

##### 1-D

In [6]:
a = [1,2,3]
arr_1 = np.array(a)
print(arr_1)

[1 2 3]


In [7]:
arr_1.ndim

1

In [8]:
arr_1.shape

(3,)

#### 2-D

In [9]:
a = [[1,2,3]]
arr_2 = np.array(a)
print(arr_2)

[[1 2 3]]


In [10]:
arr_2.ndim

2

In [11]:
arr_2.shape

(1, 3)

### Funtions for creating 1-D array

#### Arrange
* arrange is an array-valued version of the built-in python range function
* Syntax: np.arange(start,end,step)  

In [12]:
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


#### Linspace

* return evenly spaces numbers over a specified interval.
* Syntax: np.linspace(start,end,num_of_samples)

In [13]:
np.linspace(1,5,5)

array([1., 2., 3., 4., 5.])

#### Zeros

* Generate arrays of zeros
* Syntax: np.zeros(shape)

In [14]:
np.zeros(2, )

array([0., 0.])

#### Ones 

* Genrate arrays of ones
* Suntax: np.ones(shape)

#### random.randint

* Return random integers from start(inclusive) to end(exclusive)
* Syntax: np.random.randint(start,end,num_of_samples)

In [15]:
 np.random.randint(1,1000,5)

array([436, 699, 280, 720, 120])

#### Accessing Elemnets/Extracting the values 

1. Accessing a single value through indexing
2. Accessing a multiple values based on slicing
3. Accessing a multiple values based on slicing
4. Accessing a multiple values based pn condition 

In [16]:
import numpy as np
a = np.arange(10, 51, 10)
print(a)

[10 20 30 40 50]


1. Accessing a single value through indexing

In [17]:
# positive indexing 
a[1]

20

In [18]:
#Negative indexing 
a[-1]

50

2. Accessing multiple values through slicing 

In [19]:
a[1:5:2]

array([20, 40])

In [20]:
a[-1:-4:-1]

array([50, 40, 30])

3. Accesiing multiple vallues based on indexing

   * Sysntax : Array(list of index numbers)

In [21]:
a[[0,3,2,4]]

array([10, 40, 30, 50])

4. Accessing a multiple values based on condition(mask indexing or fancy indexing)

Syntax: Array(condition)

-- first it will check the condtion, the item which satisfyies the condition (means which item gives true for the condtion)that item will be selected  

In [22]:
a = np.array([45,46,47])
a[a%2==0]

array([46])

#### Modifies the values in numpy 

add a single value in a array
- Syntax : np.append(araay,value)

In [23]:
a = np.array([45,46,47])
a1 = np.append(a,484)
print(a1)

[ 45  46  47 484]


add amultiple values in a array 

In [24]:
a = np.array([45,46,47])
a2 = np.append(a,[484,494,410])
print(a2)

[ 45  46  47 484 494 410]


replacing a single value in 1-D array 

Sysntax: array[index] = value 

In [25]:
a2[5]=411
print(a2)

[ 45  46  47 484 494 411]


Replacing multiple values with a single value in a array 

In [26]:
a2[[1,2]]=20
print(a2)

[ 45  20  20 484 494 411]


Replacing a multiple values with multiple values 

In [27]:
a2[[1,2]]=[46,47]
print(a2)

[ 45  46  47 484 494 411]


delete a single value in a array 

Sysntax: np.delete(array, index number)

In [28]:
a3= np.delete(a2,3)
print(a3)

[ 45  46  47 494 411]


delete multple values in a array 

Syntax: Sysntax: np.delete(array, [muutiple index numbers])

In [29]:
a4 = np.delete(a3,[3,4])
print(a4)

[45 46 47]


copy array 

In [30]:
a = np.array([1,2,3,4])
b = a.copy() 
b[0]=10
print(a)
print(b)

[1 2 3 4]
[10  2  3  4]


Sorting of an array 

In [31]:
a = np.array([6,7,3,2,5,4])
b = np.sort(a)
print(b)

[2 3 4 5 6 7]


#### Operations

Arithmetic operations

In [32]:
a = np.array([6,7,3,2,5,4])
b = a+10
print(b)


[16 17 13 12 15 14]


In [33]:
c=a+0
print(c)

[6 7 3 2 5 4]


In [34]:
d = a**2
print(d)

[36 49  9  4 25 16]


In [35]:
print(a+b)

[22 24 16 14 20 18]


In [36]:
print(a-b)

[-10 -10 -10 -10 -10 -10]


In [37]:
print(a*d)

[216 343  27   8 125  64]


comparision operators

In [38]:
a==c

array([ True,  True,  True,  True,  True,  True])

In [39]:
c>=a

array([ True,  True,  True,  True,  True,  True])

In [40]:
np.array_equal(a, b)

False

In [41]:
np.array_equal(a, c)

True

Mathematical operations

In [42]:
np.exp(a)

array([ 403.42879349, 1096.63315843,   20.08553692,    7.3890561 ,
        148.4131591 ,   54.59815003])

In [43]:
np.log(a)

array([1.79175947, 1.94591015, 1.09861229, 0.69314718, 1.60943791,
       1.38629436])

In [44]:
print(a)

[6 7 3 2 5 4]


In [45]:
import warnings
warnings.simplefilter("ignore")

### 2-D Numpy Array

Multiple of 1-D 

In [46]:
b = np.array([[1,2,3],[4,5,6,]])
print(b)

[[1 2 3]
 [4 5 6]]


In [47]:
b.ndim

2

In [48]:
b.shape

(2, 3)

In [49]:
np.zeros((3,3 )) # by default it will take float dtype 

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [50]:
np.zeros((3,3), dtype=int)


array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [51]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [52]:
# identity matrix
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [53]:
#diagonal matrix
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [54]:
# diagonal matrix
a = np.array([[1,2,3],[3,4,5]])
np.diag(a)

array([1, 4])

In [56]:
a = np.array([[10,20,30,40],[50,60,70,80],[90,80,60,30]])
print(a)

[[10 20 30 40]
 [50 60 70 80]
 [90 80 60 30]]


indexing of 2-D array

In [57]:
a[0]   # all columns by default 

array([10, 20, 30, 40])

In [58]:
a[2,2]

60

In [59]:
a[1,2]

70

In [63]:
a[1:3]

array([[50, 60, 70, 80],
       [90, 80, 60, 30]])

In [68]:
#assigning value in 2-D array
a[1]=[20,30,40,50]
a

array([[20, 30, 40, 50],
       [20, 30, 40, 50],
       [20, 30, 40, 50]])

In [70]:
a[0,2]=500
a

array([[ 20,  30, 500,  50],
       [ 20,  30,  40,  50],
       [ 20,  30,  40,  50]])

Flattening - converting nd array to 1-D array 

In [72]:
a = np.array([[0,1,2],[3,4,5]])
print(a)

b = a.ravel()
print(b)

[[0 1 2]
 [3 4 5]]
[0 1 2 3 4 5]


Reshape Array 

In [73]:
arr=np.arange(6)
print(arr)
print(arr.shape)

[0 1 2 3 4 5]
(6,)


In [74]:
a1 = arr.reshape(2,3)
print(a1)

[[0 1 2]
 [3 4 5]]


In [75]:
a1.shape

(2, 3)

##### Sort

In [6]:
# sorting along an axis: axis=1--->row, axis=0----->column
import numpy as np
a = np.array([[2,5,3],[7,4,3],[9,4,3]])
b = np.sort(a,axis=0)
print(b)

[[2 4 3]
 [7 4 3]
 [9 5 3]]


In [3]:
import numpy as np
a = np.array([[1,2],[3,4],[5,6]])
b = np.array([[9,8],[7,6],[5,4]])
# adding a and b
print(a+b)

[[10 10]
 [10 10]
 [10 10]]


In [4]:
# dot product--> multiply a and b 9elemntwise multiplcation )
a*b

array([[ 9, 16],
       [21, 24],
       [25, 24]])

In [7]:
a = np.array([[1,2],[3,4]])
b = np.array([[9,8],[7,6]])
# matrix multiplcation 
np.matmul(a, b)

array([[23, 20],
       [55, 48]])

In [11]:
np.concatenate((a,b), axis=0)

array([[1, 2],
       [3, 4],
       [9, 8],
       [7, 6]])

In [13]:
#vertical stack         # equal to np.concatenate(a,b),axis=0
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [9, 8],
       [7, 6]])

In [14]:
np.concatenate((a,b), axis=1)

array([[1, 2, 9, 8],
       [3, 4, 7, 6]])

In [15]:
#horizontal stack         # equal to np.concatenate(a,b),axis=1
np.hstack((a,b))

array([[1, 2, 9, 8],
       [3, 4, 7, 6]])